name: build

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - '**'
      - '!.github/workflows/*'
      - '.github/workflows/release.yml'
      - '!.gitignore'
      - '!LICENSE'
      - '!README.md'

jobs:
  build:
    uses: opengood-ai/central-workflows/.github/workflows/python-package-build.yml@main
    with:
      run-code-coverage: true
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
