name: release

on:
  pull_request:
    types:
      - closed
      - labeled
    branches:
      - main
    paths-ignore:
      - .github/workflows/*
      - .gitignore
      - LICENSE
      - README.md

jobs:
  release-build:
    uses: opengood-ai/central-workflows/.github/workflows/python-release-build.yml@main
    with:
      git-email: ${{ vars.GIT_EMAIL }}
      git-user: ${{ vars.GIT_USER }}
    secrets:
      workflow-token: ${{ secrets.WORKFLOW_TOKEN }}

  py-pi-release:
    name: Python PyPI Release
    needs: [ release-build ]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.repository.name }}
    permissions:
      contents: read
      id-token: write
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release') && github.event.pull_request.merged == true }}
    steps:
      - name: Download Distribution Packages
        uses: actions/download-artifact@v8.0.1
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish Distribution Package
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          verbose: true

  release:
    uses: opengood-ai/central-workflows/.github/workflows/python-release.yml@main
    needs: [ py-pi-release ]
    secrets:
      workflow-token: ${{ secrets.WORKFLOW_TOKEN }}
