name: local-update-actions

on:
  workflow_dispatch:
  schedule:
    # Automatically run every Sunday at midnight
    - cron: '0 0 * * 0'

jobs:
  local-update-actions:
    uses: opengood-ai/central-workflows/.github/workflows/workflow-update-actions.yml@main
    with:
      git-email: ${{ vars.GIT_EMAIL }}
      git-user: ${{ vars.GIT_USER }}
    secrets:
      workflow-token: ${{ secrets.WORKFLOW_TOKEN }}
